### ISSUE TITLE
could not retrive the dcnn model for lung segmentation

### ISSUE THREAD

**Issue by kiwixiao** [acil-bwh/CIPDocker#2]
Dear developer

When I am following the script, it says can not download the machine learning model to do the lung lobe segmentation.
Error: lung_segmentation_axial.hdf5 not found, downloading, then says AccessDenied.

When I trying to access the raw URL on AWS in the dcnn_model_manager.py, it says access denied.
Would you please help me double check the model is still open for download?
Many thanks.

**Comment by rsanjoseestepar** [comment]
Hello,

Right now, direct download of the models is not available. If you want to use the dcnn lung segmentation, I would recommend the ChestImagingPlatform docker, available at https://hub.docker.com/r/acilbwh/chestimagingplatform
The model is embedded in the docker image, so no further downloading is needed. How to extract a lung segmentation is explained as an example use case in the docker documentation.

Kind regards
